### ISSUE TITLE
Feature request - możliwość dodawania okienka do wypełnienia

### ISSUE THREAD

**Issue by Janniedospial** [watchdogpolska/prezydent.siecobywatelska.pl#1]
Chodzi o dodanie możliwości, w razie potrzeby, dodania okienka do wypełnienia z adresem, aby petycja miała znamiona wniosku z kpa. Do stosowania tylko przy niektórych petycjach, w większości tego nie będzie, także normalnie okienka na adres nie powinno być, a jeśli je potrzeba - możnaby je "włączać". Czyli możliwość customizowania :) liczby i opisu okienek.

**Comment by ad-m** [comment]
See watchdogpolska/django-one-petition#5
